"""add ticket_price to events

Revision ID: 0f53f9179ad7
Revises: 71d6f42df7bf
Create Date: 2026-08-16 11:47:41.883452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f53f9179ad7'
down_revision: Union[str, None] = '71d6f42df7bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('ticket_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'ticket_price')
    # ### end Alembic commands ###
