"""add_profile_verification_and_fields

Revision ID: 12b32b6e7338
Revises: ed302517dd08
Create Date: 2026-08-15 22:39:01.216501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b32b6e7338'
down_revision: Union[str, None] = 'ed302517dd08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('university', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('zodiac_sign', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('verification_status', sa.String(length=50), nullable=False, server_default='unverified'))
    op.add_column('users', sa.Column('looking_for', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('about_me_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about_me_prompt')
    op.drop_column('users', 'looking_for')
    op.drop_column('users', 'verification_status')
    op.drop_column('users', 'zodiac_sign')
    op.drop_column('users', 'university')
    # ### end Alembic commands ###
