"""add match feedback and user trust score

Revision ID: 3952b2d2ec37
Revises: 172fc99aee07
Create Date: 2026-08-15 13:19:23.326297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3952b2d2ec37'
down_revision: Union[str, None] = '172fc99aee07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('rater_id', sa.Integer(), nullable=False),
    sa.Column('rated_id', sa.Integer(), nullable=False),
    sa.Column('met_in_person', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['rated_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'rater_id')
    )
    op.create_index(op.f('ix_match_feedback_match_id'), 'match_feedback', ['match_id'], unique=False)
    op.add_column('users', sa.Column('trust_score', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('users', 'trust_score', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trust_score')
    op.drop_index(op.f('ix_match_feedback_match_id'), table_name='match_feedback')
    op.drop_table('match_feedback')
    # ### end Alembic commands ###
