"""add notified_at to match_feedback

Revision ID: 3fea61cf58b4
Revises: 3952b2d2ec37
Create Date: 2026-08-15 13:23:05.393023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fea61cf58b4'
down_revision: Union[str, None] = '3952b2d2ec37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_feedback', sa.Column('notified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_feedback', 'notified_at')
    # ### end Alembic commands ###
