"""create swipes table

Revision ID: 615cd1e08371
Revises: 6b5fe25c3b73
Create Date: 2026-08-11 11:41:43.911713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '615cd1e08371'
down_revision: Union[str, None] = '6b5fe25c3b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swiper_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('LIKE', 'PASS', name='swipedirection'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['swiper_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('swiper_id', 'target_id', 'event_id')
    )
    op.create_index(op.f('ix_swipes_created_at'), 'swipes', ['created_at'], unique=False)
    op.create_index(op.f('ix_swipes_swiper_id'), 'swipes', ['swiper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swipes_swiper_id'), table_name='swipes')
    op.drop_index(op.f('ix_swipes_created_at'), table_name='swipes')
    op.drop_table('swipes')
    # ### end Alembic commands ###
