"""add referral fields to users

Revision ID: 6b98d7a27232
Revises: 3fea61cf58b4
Create Date: 2026-08-15 15:53:33.364091

"""
import secrets
import string
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b98d7a27232'
down_revision: Union[str, None] = '3fea61cf58b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_ALPHABET = string.ascii_uppercase + string.digits


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_code', sa.String(length=12), nullable=True))
    op.add_column('users', sa.Column('referred_by_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('bonus_swipe_credits', sa.Integer(), nullable=False, server_default='0'))
    op.create_foreign_key(None, 'users', 'users', ['referred_by_id'], ['id'])
    # ### end Alembic commands ###

    connection = op.get_bind()
    existing_ids = [row[0] for row in connection.execute(sa.text("SELECT id FROM users")).fetchall()]
    used_codes: set[str] = set()
    for user_id in existing_ids:
        while True:
            code = "".join(secrets.choice(_ALPHABET) for _ in range(7))
            if code not in used_codes:
                used_codes.add(code)
                break
        connection.execute(
            sa.text("UPDATE users SET referral_code = :code WHERE id = :id"),
            {"code": code, "id": user_id},
        )

    op.alter_column('users', 'referral_code', nullable=False)
    op.alter_column('users', 'bonus_swipe_credits', server_default=None)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_column('users', 'bonus_swipe_credits')
    op.drop_column('users', 'referred_by_id')
    op.drop_column('users', 'referral_code')
    # ### end Alembic commands ###
