"""add ticket fields and event is_paid

Revision ID: 71d6f42df7bf
Revises: a35bf0b0b4ec
Create Date: 2026-08-16 01:10:35.510243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d6f42df7bf'
down_revision: Union[str, None] = 'a35bf0b0b4ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_attendances', sa.Column('ticket_image_url', sa.String(length=500), nullable=True))
    op.add_column('event_attendances', sa.Column('ticket_decoded_text', sa.String(length=500), nullable=True))
    op.add_column('event_attendances', sa.Column('ticket_verified_at', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('is_paid', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'is_paid')
    op.drop_column('event_attendances', 'ticket_verified_at')
    op.drop_column('event_attendances', 'ticket_decoded_text')
    op.drop_column('event_attendances', 'ticket_image_url')
    # ### end Alembic commands ###
