"""add_premium_social_features

Revision ID: a226ac46b852
Revises: cb29e16630f0
Create Date: 2026-08-15 23:02:33.675607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a226ac46b852'
down_revision: Union[str, None] = 'cb29e16630f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_attendances', sa.Column('status', sa.String(length=50), server_default='approved', nullable=False))
    op.add_column('events', sa.Column('is_group_event', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('events', sa.Column('max_attendees', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('messages', sa.Column('message_type', sa.String(), server_default='text', nullable=False))
    op.add_column('messages', sa.Column('media_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('voice_note_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'voice_note_url')
    op.drop_column('messages', 'media_url')
    op.drop_column('messages', 'message_type')
    op.drop_column('matches', 'is_active')
    op.drop_column('events', 'max_attendees')
    op.drop_column('events', 'is_group_event')
    op.drop_column('event_attendances', 'status')
    # ### end Alembic commands ###
