"""add checked_in_at and phone_verification_codes

Revision ID: a35bf0b0b4ec
Revises: b7b3405aa14e
Create Date: 2026-08-16 00:24:14.839018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a35bf0b0b4ec'
down_revision: Union[str, None] = 'b7b3405aa14e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_verification_codes_user_id'), 'phone_verification_codes', ['user_id'], unique=False)
    op.add_column('event_attendances', sa.Column('checked_in_at', sa.DateTime(), nullable=True))

    # phone_number/phone_verified are added nullable first so existing rows don't
    # violate NOT NULL, backfilled with a unique placeholder, then locked down --
    # real phone numbers for pre-existing accounts aren't known.
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.execute("UPDATE users SET phone_number = 'unknown-' || id WHERE phone_number IS NULL")
    op.alter_column('users', 'phone_number', nullable=False)
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone_verified')
    op.drop_column('users', 'phone_number')
    op.drop_column('event_attendances', 'checked_in_at')
    op.drop_index(op.f('ix_phone_verification_codes_user_id'), table_name='phone_verification_codes')
    op.drop_table('phone_verification_codes')
    # ### end Alembic commands ###
