"""add_profile_fields

Revision ID: b2577480ae3a
Revises: c88829a12345
Create Date: 2026-08-17 23:36:38.634462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2577480ae3a'
down_revision: Union[str, None] = 'c88829a12345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('users', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('languages_spoken', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")))
    op.add_column('users', sa.Column('political_views', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('beliefs', sa.String(length=50), nullable=True))
    op.alter_column('users', 'hobbies',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'hobbies',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_column('users', 'beliefs')
    op.drop_column('users', 'political_views')
    op.drop_column('users', 'languages_spoken')
    op.drop_column('users', 'height')
    op.alter_column('events', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
