"""add_boost_columns

Revision ID: b7b3405aa14e
Revises: a226ac46b852
Create Date: 2026-08-15 23:31:49.226902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7b3405aa14e'
down_revision: Union[str, None] = 'a226ac46b852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('boosted_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('boosts_balance', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('extra_super_likes', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'extra_super_likes')
    op.drop_column('users', 'boosts_balance')
    op.drop_column('users', 'boosted_until')
    # ### end Alembic commands ###
