"""add accepted_terms_at to users

Revision ID: c767b59dd31d
Revises: 8956204688d8
Create Date: 2026-08-15 01:34:18.303760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c767b59dd31d'
down_revision: Union[str, None] = '8956204688d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accepted_terms_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accepted_terms_at')
    # ### end Alembic commands ###
