"""add event_attendances table

Revision ID: cb29e16630f0
Revises: 12b32b6e7338
Create Date: 2026-08-15 22:53:25.806949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb29e16630f0'
down_revision: Union[str, None] = '12b32b6e7338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_attendances_event_user')
    )
    op.create_index(op.f('ix_event_attendances_event_id'), 'event_attendances', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_attendances_user_id'), 'event_attendances', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_attendances_user_id'), table_name='event_attendances')
    op.drop_index(op.f('ix_event_attendances_event_id'), table_name='event_attendances')
    op.drop_table('event_attendances')
    # ### end Alembic commands ###
