"""add event_credits_balance to users

Revision ID: dfafb3be1554
Revises: 29105a09ada6
Create Date: 2026-08-16 13:51:48.661554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfafb3be1554'
down_revision: Union[str, None] = '29105a09ada6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', sa.Column('event_credits_balance', sa.Integer(), nullable=False, server_default='0')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'event_credits_balance')
    # ### end Alembic commands ###
