"""add date_of_birth and occupation to users

Revision ID: ed302517dd08
Revises: 6b98d7a27232
Create Date: 2026-08-15 16:34:41.907956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed302517dd08'
down_revision: Union[str, None] = '6b98d7a27232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('occupation', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'occupation')
    op.drop_column('users', 'date_of_birth')
    # ### end Alembic commands ###
